services:
  # DATABASE
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - viza-net

  # REDIS CACHE
  redis:
    image: redis:alpine
    restart: always
    networks:
      - viza-net

  # FASTIFY BACKEND
  api:
    build: ./server
    restart: always
    env_file: .env   # <--- Load global .env
    depends_on:
      - db
      - redis
    networks:
      - viza-net
    ports:
      - "8000:8000"

  # NEXT.JS CLIENT
  web:
    build: ./client
    restart: always
    ports:
      - "80:3000"
    environment:
      - NEXT_FONT_GOOGLE_OFFLINE=true
      - PORT=3000
      - NEXT_PUBLIC_API_URL=http://167.71.184.43:8000
    env_file: .env
    depends_on:
      - api
    networks:
      - viza-net

networks:
  viza-net:
    driver: bridge

volumes:
  pgdata:
