services:
  # DATABASE
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - viza-net

  # FASTIFY BACKEND
  api:
    build: ./server
    restart: always
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      PORT: 8000
      HOST: 0.0.0.0 
      # Updated to port 80 to match the new Client URL
      CLIENT_URL: http://167.71.184.43
    depends_on:
      - db
    networks:
      - viza-net
    ports:
      - "8000:8000"

  # NEXT.JS CLIENT
  web:
    build: ./client
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: http://167.71.184.43:8000
    depends_on:
      - api
    networks:
      - viza-net
    ports:
      - "80:3000"  # <--- FIX: Visitors now use standard HTTP (Port 80)

networks:
  viza-net:
    driver: bridge

volumes:
  pgdata:
